### ISSUE TITLE
请问能否分装成一个包，发布到npm，直接安装使用？

### ISSUE THREAD

**Issue by BEIBEI123** [haixin-fang/starfish-vue3-lowcode#2]
如题

**Comment by haixin-fang** [comment]
@BEIBEI123 目前发布了starfish-editor包在npm中使用,可以进行直接安装,可以参考[https://github.com/haixin-fang/starfish-vue3-lowcode/tree/master/playground](https://github.com/haixin-fang/starfish-vue3-lowcode/tree/master/playground),里面就是通过包的形式进行使用
